### ISSUE TITLE
Improve how the AI specifies where it wants to go

### ISSUE THREAD

**Issue by sartak** [TAEB/TAEB#4]
We should work in terms of "I want to go to (x, y)" rather than "I want you to go up" "left" "left" "left". That way we can get things like HJKLYUBN and _ travel.

This work may already be done!

**Comment by doy** [comment]
This is already done, and we do already use it if we ever get a controlled teleport (if i remember correctly). We actually explicitly decided against travel because it's not completely safe (it can run you into monsters and such), but that may be a decision worth revisiting.
