### ISSUE TITLE
`radiate` may be broken

### ISSUE THREAD

**Issue by doy** [TAEB/TAEB#57]
Not sure about this, but Projectile doesn't figure out to throw things at monsters that it stepped away from with Kite, and I can't see any reason why it shouldn't.

**Comment by sartak** [comment]
I had a look but I couldn't see anything wrong with radiate. The only potential thing was there was no explicit `return` at the end so radiate might've been returning results when there shouldn't have been any. But that doesn't fix the symptom you're describing.
