### ISSUE TITLE
"You hear a door open" is a giveaway for Minetown

### ISSUE THREAD

**Issue by sartak** [TAEB/TAEB#73]
That's usually how I figure it out, when it's the dark, miney map.

**Comment by doy** [comment]
Could have sworn we already did this...

**Comment by sartak** [comment]
Minetown detection works by tile type, not by message. We currently don't parse "You hear a door open" :)

**Comment by sartak** [comment]
Oh, looks like we identify shop messages (like you hear someone cursing about thieves or whatever)

**Comment by doy** [comment]
Ah, that's probably what it was.
