### ISSUE TITLE
single step mode

### ISSUE THREAD

**Issue by doy** [TAEB/TAEB#82]
Didn't we used to have one of these?

**Comment by doy** [comment]
We did, but: "Remove single_step mode, I've never seen it used and shouldn't be part of TAEB.pm anyway". What's the right thing to do here?

**Comment by sartak** [comment]
The only thing I can think of is that I may have felt single-step mode should have been a TAEB::Debug-level feature

**Comment by doy** [comment]
Added a more general watchpoint feature under TAEB::Debug, which should be able to handle this use case as well as a lot of others.
